### ISSUE TITLE
DEB, Flatpak

### ISSUE THREAD

**Issue by Adi1200** [diamondburned/gtkcord4#67] opened 2022-09-28 23:29 UTC
It would be much easier to install gtkcord as a deb or flatpak instead of using the binary file

**Comment by diamondburned** [comment] 2022-09-28 23:34
Duplicate of https://github.com/diamondburned/gtkcord4/issues/7 and maybe https://github.com/diamondburned/gtkcord4/issues/49.

I won't be packaging for any particular distro; I don't personally use any of them. You'll have to rely on the community to do so. The pre-built binaries are all that I can provide atm.

**Closed by diamondburned** 2022-09-28 23:34 UTC
