### ISSUE TITLE
Feature - VC Support

### ISSUE THREAD

**Issue by 32bitx64bit** [diamondburned/gtkcord4#155] opened 2023-09-11 21:54 UTC
VC support would basically make the discord app useless.

So I hope this app can get some sort of VC support soon, as its the only thing stopping many from switching to this instead.

**Comment by diamondburned** [comment] 2023-09-26 08:22
Duplicate of https://github.com/diamondburned/gtkcord4/issues/97.

**Closed by diamondburned** 2023-09-26 08:22 UTC
