### ISSUE TITLE
Audio call support?

### ISSUE THREAD

**Issue by Diegovsky** [diamondburned/gtkcord4#106] opened 2023-02-07 14:02 UTC
I'm surprised how well gtkcord4 looks and feels. You have a lot implemented currently and I would love to see Audio Calls/Channels support. If you have resources on how to do it, I would be willing to send a PR :)

**Comment by Newbytee** [comment] 2023-02-07 15:29
Maybe look at https://github.com/diamondburned/gtkcord4/issues/97.

**Comment by diamondburned** [comment] 2023-02-08 00:32
Unfortunately, voice support is not trivial to work on and will require a lot of fiddling. I am personally OK with opening the official client every now and then for voice chat, so I won't be needing voice support in gtkcord4 myself.

Closing this issue since it's a duplicate of #97.

**Closed by diamondburned** 2023-02-08 00:32 UTC

**Comment by Diegovsky** [comment] 2023-02-09 14:10
Sorry, didn't mean to open a duplicate. Thanks for the quick response though :)
