### ISSUE TITLE
[Request] Publish the app on Flathub

### ISSUE THREAD

**Issue by Radical4ever** [diamondburned/gtkcord4#50] opened 2022-07-28 20:50 UTC
HI, i like a lot this app and how's developing, so when it gets to a more stable release, is it possible to be published on flathub?. thank you

**Comment by diamondburned** [comment] 2022-07-29 01:19
Duplicate of https://github.com/diamondburned/gtkcord4/issues/7.

**Closed by diamondburned** 2022-07-29 01:19 UTC
