### ISSUE TITLE
Missing compiled binaries in latest release

### ISSUE THREAD

**Issue by txtsd** [diamondburned/gtkcord4#140] opened 2023-06-02 04:56 UTC
[v0.0.11](https://github.com/diamondburned/gtkcord4/releases/tag/v0.0.11) does not have compiled binary artifacts like the other releases do.

**Comment by diamondburned** [comment] 2023-06-02 15:25
It seems to be caused by the cmd/cgo patches that I have in the Go compiler used for this build, which made the build very unstable and indeterministic:

```
# github.com/diamondburned/gotk4/pkg/gio/v2
vendor/github.com/diamondburned/gotk4/pkg/gio/v2/gsettings_export.go:56:79: syntax error: mixed named and unnamed parameters
vendor/github.com/diamondburned/gotk4/pkg/gio/v2/gsettings_export.go:110:31: syntax error: unexpected _Ciconst_TRUE, expected )
vendor/github.com/diamondburned/gotk4/pkg/gio/v2/gsettings_export.go:110:15: syntax error: unexpected ) at end of statement
```

There are two possible fixes here: either rollback to Go 1.19 which doesn't have this behavior, or the pipeline takes at least twice as long to build.

**Comment by diamondburned** [comment] 2023-06-03 04:42
I created https://github.com/diamondburned/gtkcord4/releases/tag/v0.0.11-1 to fix this.

**Comment by diamondburned** [comment] 2023-06-03 10:11
Closing since the binaries are there now.

**Closed by diamondburned** 2023-06-03 10:11 UTC
