### ISSUE TITLE
Consolidate Adwaita & LibAdwaita builds

### ISSUE THREAD

**Issue by ThatOneCalculator** [diamondburned/gtkcord4#72] opened 2022-10-03 22:15 UTC
Most people who use GTK4 use LibAdwaita, and having this match the rest of one's system is probably one of the main draws of having a GTK client in the first place

**Comment by diamondburned** [comment] 2022-10-04 01:54
I'm not willing to make libadwaita the default.

Regarding theme inconsistency, GNOME GTK4's default stylesheet not following Adwaita is frankly not my problem. It is a decision that the GNOME developers explicitly made to alienate non-libadwaita applications, and I don't see that as a welcoming decision to make for the GTK application ecosystem.

**Comment by ThatOneCalculator** [comment] 2022-10-04 02:04
Is there any way a switcher could be provided in the settings in the app rather than relying on different builds, then?

**Comment by diamondburned** [comment] 2022-10-04 02:22
There's no way to do that without statically linking libadwaita during compile.

Well, that's not true. There technically is a way: by using libgirepository or something similar and hook to the library at runtime. This requires a lot of fiddling though, and may potentially be explosive.

gotk4 initially had progress on libgirepository code generation. However, most of that has been regressed by subclassing code, so that probably have to be fixed first. Whether they'll be fixed before or after subclassing, I have no clue. I'm not actively working on neither of them right now, since the memory leak issues is a bigger issue.

**Comment by DodoLeDev** [comment] 2022-11-01 00:32
### Hi @diamondburned!
I've tried both versions of your GTKcord app (gtk4 & Libadwaita ones), and I don't understand the reasons that prevent you from completely moving to Libadwaita… :thinking:

The Libadwaita version seems so polished! :star_struck: And I don't see any major graphical difference…
If you worry about not being able to control the theme used by your app, here are some links that can help you:
- :link: [Force the dark theme for your Libadwaita app](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.2/method.StyleManager.set_color_scheme.html)
- :link: [Setting a custom Libadwaita theme](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/styles-and-appearance.html#custom-styles)

*Hoping to have helped you!*

**Comment by mossymossmoss** [comment] 2022-11-16 17:20
This app seems like a great desktop client, ticks all of the boxes, except from the libadwaita part. The GTK3 UI leaves it looking out-of-place and a bit dated. Functionality wise, the app is great, but I would consider looking more into libadwaita, even just for the extra widgets and adaptivity features it provides

**Comment by diamondburned** [comment] 2022-11-16 21:57
gtkcord4 uses GTK4. It has the adaptive widgets needed for mobile support, and I know people who are using it on mobile.

As far as looks are concerned, that's to do with GTK4 itself. You can use a custom GTK4 theme that looks like the Adwaita theme, or you can switch to a different theme entirely (though the GNOME people would hate you for that).

**Comment by TriVoxel** [comment] 2022-11-18 01:43
> I'm not willing to make libadwaita the default.
> 
> Regarding theme inconsistency, GNOME GTK4's default stylesheet not following Adwaita is frankly not my problem. It is a decision that the GNOME developers explicitly made to alienate non-libadwaita applications, and I don't see that as a welcoming decision to make for the GTK application ecosystem.

I think they are just not concerned with updating their GTK3 theme to look like LibAdwaita. Also, this doesn't just affect 3rd party developers. For the longest time, many official Gnome apps looked out of place such as Files and Tweaks and Web. The workaround is for the user to simply download a libadwaita theme like [adwgtk3](https://github.com/lassekongo83/adw-gtk3) which is able to make all GTK3 & 4 apps look consistent. It is a trivial and well-known fix to make the interface consistent. It works remarkably well.

It seems like there is legitimate demand for both a GTK4 client, and a LibAdwaita client. Why not release both? You can offer a GTK4 download, and then a LibAdwaita client and we can have the best of both worlds. IDK how much effort that would require, but I know I would personally appreciate it, and so would the people who prefer the GTK4 app. I hate to say it, but as cool as this app is, and as much as I want to see it succeed, I don't want to use it if it looks out of place on my system and refuses to theme itself in accordance with the rest of my system. It doesn't even respect my GTK3/4 theme preferences. LibAdwaita is VERY popular despite its skeptical launch, and many users love the way it integrates so cleanly into the Gnome interface. I commend you for your efforts to differentiate your app and to do it your own way, but I think most Gnome users would appreciate a native version for their desktops. I don't understand why you are pushing back so hard like Gnome is against you. You can develop your app however you want, but when you make an app using GTK, you gotta expect that at least some users are going to be using it on Gnome, and will expect it to look and feel like Gnome. Anyways, best of luck. GTKcoord4 looks impressive, I just wish it looked like the rest of my desktop.

**Comment by diamondburned** [comment] 2022-11-18 01:53
> Why not release both? You can offer a GTK4 download, and then a LibAdwaita client and we can have the best of both worlds.

Because the CI build time is already 40-50 minutes, which is almost the CI runtime limit of 1 hour.

> I hate to say it, but as cool as this app is, and as much as I want to see it succeed, I don't want to use it if it looks out of place on my system and refuses to theme itself in accordance with the rest of my system.

That's fine. I believe that this is now impossible in current year, and the GNOME Foundation doesn't seem to care about supporting as many GTK apps as possible. That's my 2c, though.

**Comment by mossymossmoss** [comment] 2022-11-18 07:51
From what I've seen, the GNOME team have been pretty good at supporting/promiting apps for their desktop with initiatives like GNOME Circle and This Week In GNOME, but those mostly apply to applications following the most recent HIG with GTK4 and Libadwaita. I really do think that people would love this app, just that the only things holding it back are it's UI and lack of Flatpak support. If it were to use Libadwaita, I would definitely try to sort out the later 👍

**Comment by diamondburned** [comment] 2022-11-18 08:45
> I really do think that people would love this app, just that the only things holding it back are it's UI and lack of Flatpak support. If it were to use Libadwaita, I would definitely try to sort out the later +1

You can try and make a Flatpak package that has libadwaita linked to it. You don't have to rely on me supplying libadwaita binaries. This is your choice.

**Comment by diamondburned** [comment] 2022-12-27 10:23
I've decided to try and see how long it would take for GitHub Actions to build gtkcord4 both with and without libadwaita. The following issues track this:

- [ ] https://github.com/diamondburned/gtkcord4/issues/99
- [ ] https://github.com/diamondburned/gotk4-nix/issues/2

**Comment by hmenke** [comment] 2022-12-27 10:27
Maybe gomod2nix is useful for this purpose? It facilitates greater reuse of Go modules across different builds.
https://github.com/nix-community/gomod2nix
https://xeiaso.net/blog/nix-flakes-go-programs

**Comment by diamondburned** [comment] 2022-12-27 10:35
> Maybe gomod2nix is useful for this purpose? It facilitates greater reuse of Go modules across different builds.

I'll probably have to do this, otherwise even with all Nix paths cached, the `vendorSha256` will be changing quite often anyway.

**Comment by diamondburned** [comment] 2022-12-27 13:04
Nevermind, gomod2nix doesn't really help. It only helps packaging Go modules, which contain sources, but it doesn't pack build cache artifacts. I'm not sure if there's a way to do this with Nix's pure builders.

**Comment by diamondburned** [comment] 2022-12-27 13:06
To make matters worse, adding build tags into the package in Nix will likely force a full rebuild as well, since it won't be reusing the previously build derivation's build cache artifacts.

**Comment by mossymossmoss** [comment] 2023-01-07 15:01
Just tried out the packages built with GitHub actions from a few days ago and both the x86 and ARM builds work great! Here's a photo of the ARM version running on my Pinephone Pro
![image](https://user-images.githubusercontent.com/56167669/211157096-fab21275-a136-454a-9a2a-c0d22e110f5c.jpeg)

**Comment by diamondburned** [comment] 2023-01-07 15:40
> Just tried out the packages built with GitHub actions from a few days ago and both the x86 and ARM builds work great!

Neat! I already forgot about this despite me working on it yesterday. Does the libadwaita build also work?

**Comment by mossymossmoss** [comment] 2023-01-07 17:36
That is the Libadwaita build! Very excited to have a client that fits it with the rest of the apps on my phone and desktop 😄

**Comment by orowith2os** [comment] 2023-01-28 23:26
I see quite a bit of misinformation here regarding GNOME's decisions coming from @diamondburned, let me clear it up:

GNOME didn't make libadwaita theme separately to alienate non-libadwaita applications. They made it separate so that it can theme "properly" and apps can easily follow GNOME guidelines. GTK itself also doesn't have default light/dark themes whereas libadwaita does. That's not to alienate apps, that's just how the toolkits work. Providing default themes for plain GTK can also be problematic even if the GNOME project provides them, see the following.

GNOME also isn't against theming, just distros shipping themes OOTB. Doing so can increasethe breakage of apps (see the recent Manjaro issues with  Firefox and its GNOME theme, for example). Ubuntu also breaks apps when they theme  by having bad contrast. You're free to theme your own desktop, and tools are provided to make it easy, like Gradience.

If GNOME was as bad as you make it out to be, then they wouldn't provide the ability to customize at all.

**Comment by diamondburned** [comment] 2023-01-29 04:56
> as I said before Libadwaita is aimed at GNOME.

So I guess gtkcord4 doesn't support GNOME, then.

If GNOME doesn't support changing GTK4 themes, then that's GNOME's problem. It doesn't really matter what their stances are regarding application theming, but they're certainly against providing ways to change themes for those applications.

I don't think there's much "misinformation" to clear up here; their stance is obvious. It doesn't matter what they say, it matters what they do.

**Comment by TriVoxel** [comment] 2023-01-30 09:54
> > So I guess gtkcord4 doesn't support GNOME, then.
> 
> If GNOME doesn't support changing GTK4 themes, then that's GNOME's problem. It doesn't really matter what their stances are regarding application theming, but they're certainly against providing ways to change themes for those applications.

Gnome has many theming options. Libadwaita is not a GTK4 theme, so it doesn't theme GTK4 applications. It's a UI toolkit based on GTK4 with its own widgets, design guidelines, and theme. It follows Gnome's UI standards to help them (and anyone who chooses to support it) to make GTK4 apps that integrate well with Gnome. Libadwaita can be easily themed, even easier than GTK3 and 4. If you want to theme a GTK4 app on Gnome, it is as easy as installing a theme that supports GTK4 and selecting it in Gnome tweaks, just like GTK3. The problem is really just that many GTK3 themes don't support GTK4 yet, and [ADWGTK3](https://github.com/lassekongo83/adw-gtk3/) (which is a very popular way to theme all apps as Libadwaita) does not contain a GTK4 theme by default. Gnome has actually made it easier than ever for users to theme their GTK apps, and Libadwaita has made it easier for developers to create GTK4 applications that look good and fit in with native Gnome apps.

Where is all this hatred coming from? I mean, you can dislike whatever you want, but it honestly doesn't sound informed at all to me. Have you taken the time to try Gnome desktop on something like Fedora? You can install Gradience, theme the whole system however you like, even install theme packs like the "good 'ol days". However, unlike those days, apps don't break with theming now, and everything runs smoothly and looks consistent. I personally themed your app in Gnome 43 just by installing a GTK4 theme and using Gnome Tweaks...

**Comment by diamondburned** [comment] 2023-01-30 11:52
I'm not arguing this further. My stance is made clear.

I've added libadwaita builds into the CI. There's no longer a reason for this issue to be open.

**Closed by diamondburned** 2023-01-30 11:52 UTC

**Comment by ThatOneCalculator** [comment] 2023-01-30 16:49
On that note, can you please provide instructions on how to install from the CI build artifacts?

**Comment by diamondburned** [comment] 2023-01-30 21:44
> On that note, can you please provide instructions on how to install from the CI build artifacts?

There's no installer, but you just install the executable, `.desktop` file and icon files provided in the tarball. All CI artifacts will be uploaded as a Nightly pre-release, so just check the Releases page of the repository.

I'm not sure what goes where on a typical Linux system, but you should be able to just extract the `bin/` and `share/` folders inside the archive right onto `/usr`. It's probably best that you use the artifacts to make a package for your distro's package manager, though.

**Comment by ThatOneCalculator** [comment] 2023-01-30 21:54
Maybe @mossymossmoss could help as I'm not used to PostmarketOS

**Comment by diamondburned** [comment] 2023-02-09 11:30
I think from v0.0.10 onwards, I'll make libadwaita the default. My current theme works fine on libadwaita with `$GTK_THEME` at the moment. Let's hope that lasts.

**Comment by diamondburned** [comment] 2023-02-13 04:34
eab5681fb05a58a6579d9251134fd39671e25fb5 uses libadwaita by default now.
